# Generated by Django 5.1.15 on 2026-09-23 18:42

import accounts.validators
import applications.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to=applications.models.application_resume_upload_path, validators=[accounts.validators.validate_resume_file])),
                ('cover_letter', models.TextField(blank=True, default='')),
                ('additional_information', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('UNDER_REVIEW', 'Under Review'), ('SHORTLISTED', 'Shortlisted'), ('INTERVIEW_SCHEDULED', 'Interview Scheduled'), ('INTERVIEW_COMPLETED', 'Interview Completed'), ('SELECTED', 'Selected'), ('REJECTED', 'Rejected')], db_index=True, default='APPLIED', max_length=40)),
                ('match_score', models.IntegerField(default=0, help_text='Calculated match score percentage (0-100)')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
            ],
            options={
                'ordering': ['-applied_at'],
                'unique_together': {('candidate', 'job')},
            },
        ),
    ]
