# Comprehensive skill taxonomy with aliases and normalized forms

SKILL_ALIASES = {
    # Programming Languages
    'python': 'Python',
    'python3': 'Python',
    'javascript': 'JavaScript',
    'js': 'JavaScript',
    'typescript': 'TypeScript',
    'ts': 'TypeScript',
    'java': 'Java',
    'c++': 'C++',
    'cpp': 'C++',
    'c#': 'C#',
    'csharp': 'C#',
    '.net': '.NET',
    'dotnet': '.NET',
    'golang': 'Go',
    'go': 'Go',
    'ruby': 'Ruby',
    'php': 'PHP',
    'rust': 'Rust',
    'swift': 'Swift',
    'kotlin': 'Kotlin',
    'scala': 'Scala',
    'r': 'R',
    'dart': 'Dart',
    'html': 'HTML',
    'html5': 'HTML',
    'css': 'CSS',
    'css3': 'CSS',
    'sass': 'Sass',
    'scss': 'Sass',

    # Frameworks & Libraries - Frontend
    'react': 'React',
    'reactjs': 'React',
    'react.js': 'React',
    'nextjs': 'Next.js',
    'next.js': 'Next.js',
    'angular': 'Angular',
    'angularjs': 'Angular',
    'vue': 'Vue',
    'vuejs': 'Vue',
    'vue.js': 'Vue',
    'nuxt': 'Nuxt.js',
    'svelte': 'Svelte',
    'redux': 'Redux',
    'tailwind': 'Tailwind CSS',
    'tailwindcss': 'Tailwind CSS',
    'bootstrap': 'Bootstrap',
    'jquery': 'jQuery',

    # Frameworks & Libraries - Backend
    'django': 'Django',
    'flask': 'Flask',
    'fastapi': 'FastAPI',
    'express': 'Express.js',
    'expressjs': 'Express.js',
    'node': 'Node.js',
    'nodejs': 'Node.js',
    'node.js': 'Node.js',
    'spring': 'Spring Boot',
    'springboot': 'Spring Boot',
    'spring boot': 'Spring Boot',
    'laravel': 'Laravel',
    'ruby on rails': 'Ruby on Rails',
    'rails': 'Ruby on Rails',
    'asp.net': 'ASP.NET',

    # Databases
    'sql': 'SQL',
    'mysql': 'MySQL',
    'postgresql': 'PostgreSQL',
    'postgres': 'PostgreSQL',
    'mongodb': 'MongoDB',
    'mongo': 'MongoDB',
    'redis': 'Redis',
    'sqlite': 'SQLite',
    'sqlite3': 'SQLite',
    'oracle': 'Oracle',
    'mssql': 'MS SQL Server',
    'cassandra': 'Cassandra',
    'dynamodb': 'DynamoDB',
    'mariadb': 'MariaDB',
    'neo4j': 'Neo4j',
    'elasticsearch': 'Elasticsearch',

    # Architecture & APIs
    'rest': 'REST API',
    'rest api': 'REST API',
    'restful': 'REST API',
    'restful api': 'REST API',
    'graphql': 'GraphQL',
    'grpc': 'gRPC',
    'microservices': 'Microservices',
    'websockets': 'WebSockets',
    'soap': 'SOAP',

    # Cloud & DevOps
    'git': 'Git',
    'github': 'GitHub',
    'gitlab': 'GitLab',
    'docker': 'Docker',
    'kubernetes': 'Kubernetes',
    'k8s': 'Kubernetes',
    'aws': 'AWS',
    'amazon web services': 'AWS',
    'azure': 'Azure',
    'microsoft azure': 'Azure',
    'gcp': 'GCP',
    'google cloud': 'GCP',
    'ci/cd': 'CI/CD',
    'cicd': 'CI/CD',
    'jenkins': 'Jenkins',
    'terraform': 'Terraform',
    'ansible': 'Ansible',
    'linux': 'Linux',
    'nginx': 'Nginx',
    'apache': 'Apache',

    # Data Science, ML & AI
    'machine learning': 'Machine Learning',
    'ml': 'Machine Learning',
    'deep learning': 'Deep Learning',
    'nlp': 'NLP',
    'natural language processing': 'NLP',
    'computer vision': 'Computer Vision',
    'tensorflow': 'TensorFlow',
    'pytorch': 'PyTorch',
    'keras': 'Keras',
    'pandas': 'Pandas',
    'numpy': 'NumPy',
    'scikit-learn': 'Scikit-Learn',
    'sklearn': 'Scikit-Learn',
    'data analysis': 'Data Analysis',

    # Testing & Methods
    'agile': 'Agile',
    'scrum': 'Scrum',
    'tdd': 'TDD',
    'unit testing': 'Unit Testing',
    'pytest': 'Pytest',
    'jest': 'Jest',
    'cypress': 'Cypress',
    'selenium': 'Selenium',
    'postman': 'Postman',
    'jira': 'Jira',
}
