# Generated by Django 5.1.15 on 2026-09-23 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('department', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField()),
                ('responsibilities', models.TextField(blank=True, default='')),
                ('qualifications', models.TextField(blank=True, default='')),
                ('location', models.CharField(max_length=255)),
                ('job_type', models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('REMOTE', 'Remote'), ('CONTRACT', 'Contract'), ('INTERNSHIP', 'Internship')], default='FULL_TIME', max_length=50)),
                ('experience_min', models.IntegerField(default=0)),
                ('experience_max', models.IntegerField(default=10)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('required_skills', models.TextField(help_text='Comma-separated required skills e.g., Python, Django, SQL')),
                ('openings', models.PositiveIntegerField(default=1)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected'), ('DISABLED', 'Disabled')], db_index=True, default='PENDING_APPROVAL', max_length=30)),
                ('admin_feedback', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='jobs.job')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('candidate', 'job')},
            },
        ),
    ]
